### ISSUE TITLE
There's no NuGet available yet

### ISSUE THREAD

**Issue by ellinge** [Geta/geta-optimizely-hotspotseditor#2]
There's no nuget yet for the package, I've used a self hosted for a while now but is it okey for release now?
https://nuget.optimizely.com/?q=HotspotsEditor&s=Popular&r=10&f=All

**Comment by ellinge** [comment]
Ping @marisks

**Comment by marisks** [comment]
I'll check what's missing for the release

**Comment by marisks** [comment]
The package is uploaded to nuget.optimizely.com
